Tsystem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from komax import views as komax_views

admin.site.site_header = "ADMINISTRATOR PAGE"
admin.site.site_title = "T-TECH ACCOUNTING"
admin.site.index_title = "Welcome to ADMIN PAGE"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('komax/', include('komax.urls')),
    path('foiling/', include('foiling.urls')),
    path('acct/', include('acct.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='komax/login.html'), name='login'),
    path('logout/', komax_views.Logout, name='logout'),
    path('auth/', komax_views.autho, name='auth'),
    path('check_group/', komax_views.check_group, name='check_group'),
]

acct/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('acchome/', views.Acchome, name='acchome')
]

komax/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('home/', views.KHomepage, name='KHomepage'),
    path('deletedr/<slug:cnum>', views.DeleteDR, name='kdeletedr'),
    path('closedr/<slug:cnum>', views.CloseDR, name='kclosedr'),
    path('editdr/<slug:cnum>', views.EditDR, name='keditdr'),
    path('deleteitem/<slug:id>', views.DeleteITEM, name='kdeleteitem'),
    path('edititem/<slug:id>', views.EditItem, name='kedititem'),
    path('acchome/', views.Acchome, name='kacchome'),
    path('summary/<slug:customerS>/<slug:monS>/<slug:yearS>', views.Summary, name='ksummary'),
]

komax/models.py
from django.db import models
from django.utils import timezone


class dr_form(models.Model):
    date_created = models.DateField(default=timezone.now)
    control_no = models.IntegerField(unique=True)
    customer = models.CharField(max_length=50)
    line = models.CharField(max_length=50, default='LINE')
    status = models.CharField(max_length=20, default='OPEN')
    
    def __str__(self):
        return str(self.control_no)

class dr_item(models.Model):
    product_no = models.CharField(max_length=50)
    wos_no = models.CharField(max_length=50,default='')
    first_quantity = models.IntegerField(default='')
    second_quantity = models.IntegerField(default='')
    third_quantity = models.IntegerField(default='')
    fourth_quantity = models.IntegerField(default='')
    fifth_quantity = models.IntegerField(default='')
    control_noFK = models.ForeignKey(dr_form, to_field="control_no", db_column="control_no", on_delete=models.CASCADE, default='', related_name='entries')
    
    def __str__(self):
        return str(self.product_no)
    # class Meta:
    #     verbose_name_plural = "Dies"

komax/forms.py
from django import forms
from komax.models import dr_form, dr_item
from django.utils.translation import ugettext_lazy as _


class NewDrForm(forms.ModelForm):
    customerCHOICES=[('HONDA','HONDA'),
                     ('IMV','IMV'),
                     ('GM','GM'),
                     ('OUTLANDER','OUTLANDER'),
                     ('CHRYSLER','CHRYSLER')]

    statusCHOICES=[('OPEN','OPEN'),
                   ('WAITING','WAITING'),
                   ('CLOSED','CLOSED')]
    

    customer = forms.ChoiceField(choices=customerCHOICES, required=True)
    status = forms.ChoiceField(choices=statusCHOICES, required=False)
    class Meta:
        model=dr_form
        fields = ['date_created', 'control_no', 'customer', 'line','status']

class NewDrItem(forms.ModelForm):
    control_noFK= forms.CharField(widget = forms.HiddenInput(), required=False)
    second_quantity = forms.IntegerField(widget = forms.HiddenInput(), initial=0, label="2ND")
    third_quantity = forms.IntegerField(widget = forms.HiddenInput(), initial=0, label="3RD")
    fourth_quantity = forms.IntegerField(widget = forms.HiddenInput(), initial=0, label="4TH")
    fifth_quantity = forms.IntegerField(widget = forms.HiddenInput(), initial=0, label="5TH")
    class Meta:
        model=dr_item
        fields = ['product_no', 'wos_no', 'first_quantity', 'second_quantity', 'third_quantity', 'fourth_quantity', 'fifth_quantity']
        # fields = ['product_no', 'wos_no', 'first_quantity', 'second_quantity', 'third_quantity', 'fourth_quantity', 'fifth_quantity', 'control_noFK']
        # raw_id_fields = ['control_noFK',]

        labels = {
            'first_quantity': _('1ST'),
            'second_quantity': _('2ND'),
            'third_quantity': _('3RD'),
            'fourth_quantity': _('4TH'),
            'fifth_quantity': _('5TH'),
            # 'control_noFK': _('Control no'),
        }
        # widgets = {
        #     'control_no': forms.TextInput(attrs={'disabled': True}),
        # }

komax/views.py
from django.shortcuts import render, redirect
from komax.models import dr_form, dr_item
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import logout
from django.contrib import messages
from komax.forms import NewDrForm, NewDrItem
import json
from django.db import connection


def check_group(request):
    if request.user.groups.filter(name='komax').exists():
        return redirect('KHomepage')
    elif request.user.groups.filter(name='foiling').exists():
        return redirect('FHomepage')
    else:
        return redirect('acchome')

def autho(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponse(json.dumps('loggedIn'), content_type="application/json")
    else: 
        return HttpResponseRedirect('/login/')

def Logout(request):
    return render(request, 'komax/logout.html')

# def dr_group(user):
#     return user.groups.filter(name='komax').exists()

# Use the above with:
@login_required
#@user_passes_test(dr_group, login_url='acchome')
def KHomepage(request):
    if request.method == 'POST':
        if request.POST.get('form_ctrl') == "new_dr":
            form = NewDrForm(request.POST)
            if form.is_valid():
                olo = form.cleaned_data['control_no']
                form.save()
                return redirect(f'/komax/editdr/{olo}')
            else:
                messages.warning(request, "Canceled: Control Number already exist!")
        if request.POST.get('form_ctrl') == "rename_dr":
            form = NewDrForm(request.POST)
            if form.is_valid():
                olo = form.cleaned_data['control_no']
                form.save()
                old_dr = request.POST.get('old_dr')
                new_dr = request.POST.get('control_no')
                n_dr = dr_form.objects.get(control_no=new_dr)
                o_dr_items = dr_item.objects.filter(control_noFK=old_dr)
                o_dr_items.update(control_noFK=n_dr)
                dr_form.objects.get(control_no=old_dr).delete()
                return redirect(f'/komax/editdr/{olo}')
            else:
                messages.warning(request, "Canceled: Control Number already exist!")
    else:
        form = NewDrForm()
    context = {
        'form':form,
        'dr_form': dr_form.objects.filter(Q(status='OPEN')| Q(status='WAITING')).order_by('control_no'),
        #'dr_form': dr_form.objects.all().order_by('control_no'),
    }
    return render(request, 'komax/home.html', context)

def CloseDR(request, cnum):
    try:
        olo = dr_form.objects.get(control_no=cnum)
        olo.status = "CLOSED"
        olo.save()
        messages.success(request, f'{cnum}: Succesfully Closed!')
    except:
        messages.success(request, f'DR already Closed by another User!')
    return redirect('KHomepage')

def DeleteDR(request, cnum):
    try:
        dr_form.objects.get(control_no=cnum).delete()
        messages.info(request, f'{cnum}: Succesfully deleted!')
    except:
        messages.info(request, f'DR already Deleted by another User!')
    return redirect('KHomepage')
    
def EditDR(request, cnum):
    if request.method == 'POST':
        if request.POST.get('form_ctrl') == "dr_form":
            form = NewDrForm(request.POST, instance=dr_form.objects.get(control_no=cnum))
            # form = NewDrForm(request.POST, instance=dr_form.objects.filter(control_no=cnum).get(control_no=cnum))
            form1 = NewDrItem()
            if form.is_valid():
                form.save()
                return redirect('KHomepage')

        elif request.POST.get('form_ctrl') == "dr_item":
            form = NewDrForm(instance=dr_form.objects.get(control_no=cnum))
            form1 = NewDrItem(request.POST)
            new_form1 = form1.save(commit=False)
            new_form1.control_noFK = dr_form.objects.get(control_no=cnum)
            if form1.is_valid():
                # cnum=form1.cleaned_data['control_noFK']
                form1.save()
                return redirect(f'/komax/editdr/{cnum}')
    else:
        try:
            form = NewDrForm(instance=dr_form.objects.get(control_no=cnum))
            # form = NewDrForm(instance=dr_form.objects.filter(control_no=cnum).get(control_no=cnum))
            form1 = NewDrItem()
        except:
            return redirect('KHomepage')

    if request.user.username == 'komaxa':
        signed_by = "JOSIE AUTOS"
    elif request.user.username == 'komaxb':
        signed_by = "GLORIA PASTOR"
    context = {
        'form'  :   form,
        'form1' :   form1,
        'items' :   dr_item.objects.filter(control_noFK=cnum).order_by('id'),
        'signed_by' : signed_by
    }
    return render(request, 'komax/dr.html', context)

def DeleteITEM(request, id):
    cnum = dr_item.objects.get(id=id).control_noFK
    dr_item.objects.get(id=id).delete()
    # messages.info(request, f'{cnum}: Succesfully deleted!')
    return redirect(f'/komax/editdr/{cnum}')
    
def EditItem(request, id):
    if request.method == 'POST':
        form1 = NewDrItem(request.POST, instance=dr_item.objects.get(id=id))
        cnum = dr_item.objects.get(id=id)
        print(cnum.control_noFK)
        new_form1 = form1.save(commit=False)
        new_form1.control_noFK = dr_form.objects.get(control_no=f'{cnum.control_noFK}')
        if form1.is_valid():
            cnum=dr_item.objects.get(id=id).control_noFK
            form1.save()
            return redirect(f'/komax/editdr/{cnum}')
    else:
        form1 = NewDrItem(instance=dr_item.objects.get(id=id))
    context = {
        'form1' :   form1,
    }
    return render(request, 'komax/edit.html', context)

def Acchome(request):
    if request.method == 'POST':
        customerS = request.POST['customerS']
        monS = request.POST['monS']
        yearS = request.POST['yearS']
        return redirect(f'/komax/summary/{customerS}/{monS}/{yearS}')
    return render(request, 'komax/acchome.html')

def Summary(request, customerS, monS, yearS):
    customerS = customerS
    monS = monS
    yearS = yearS
    objs = dr_item.objects.raw(f"""
                                SELECT
                                    t.id,
                                    product_no,
                                    wos_no,
                                    quantity,
                                    cn,
                                    date_created,
                                    customer,
                                    status
                                FROM ( SELECT
                                        id,
                                        product_no,
                                        wos_no,
                                        (first_quantity + second_quantity + third_quantity + fourth_quantity + fifth_quantity) AS quantity,
                                        control_no AS cn,
                                        (select date_created from komax_dr_form where control_no = cn limit 1) AS date_created,
                                        (select customer from komax_dr_form where control_no = cn limit 1) AS customer,
                                        (select status from komax_dr_form where control_no = cn limit 1) AS status
                                    FROM komax_dr_item ) AS t
                                WHERE t.customer = '{customerS}' AND t.date_created LIKE '{yearS}-{monS}%%' ORDER BY cn, date_created;""")
    context = {
        'items': objs,
        'customerS' :   customerS,
        'monS'  :   monS,
        'yearS' :   yearS,
    }
    return render(request, 'komax/summary.html', context)

komax/templates/komax/dr.html
{% extends "komax/base.html" %}
{% load crispy_forms_tags %}

{% block title %}DR EDIT{% endblock title %}

{% block content %}

        
    <button id="btn_print" class="btn btn-outline-danger font-weight-bold mr-1 pl-0 pr-0" style="position:absolute; top: 5px; right: 16px; width: 65px;">Print</button>
    
    <div id="mainDrdiv" class="container-flex m-3 pl-1 pr-1 border border-dark rounded" style="height: 565px; position: relative;">

        <form method="POST" autocomplete="off">
        <div class="row">
                {% csrf_token %}
                <div class="col-3">
                    {{ form.control_no|as_crispy_field }}
                </div>
                <div class="col-4">
                    <div class="row m-0">
                        <div class="col-5 m-0 p-0 pr-3">
                            {{ form.customer|as_crispy_field }}
                        </div>
                        <div class="col-7 m-0 p-0 pl-3">
                            {{ form.line|as_crispy_field }}
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    {{ form.date_created|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.status|as_crispy_field }}
                </div>
        </div>
            <input type="hidden" name="form_ctrl" value="dr_form">
            <button type="submit" class="btn btn-outline-primary font-weight-bold m-0" id="donedr" style="position: absolute; bottom: 10px; right: 5px;">Done</button>
        </form>
        
         <table id="tabledr" class="scroll table table-bordered shadow-lg table-striped font-weight-bold table-hover p-0 mx-auto w-75">
            <thead class="thead-dark">
              <tr>
                <th class="border-bottom-0 pb-0" style="width: 72px;">SEQ.</th>
                <th class="border-bottom-0 pb-0" style="width: 300px;">PRODUCT</th>
                <th class="border-bottom-0 pb-0" style="width: 150px;">WOS</th>
                <th class="text-center" colspan=5 >QUANTITY</th>
              </tr>
              <tr>
                <th class="border-top-0 pt-0" style="width: 72px;">NO.</th>
                <th class="border-top-0 pt-0" style="width: 300px;">NO.</th>
                <th class="border-top-0 pt-0" style="width: 150px;">NO.</th>
                <th class="border-top-0" style="width: 93px;">1ST</th>
                <th class="border-top-0" style="width: 93px;">2ND</th>
                <th class="border-top-0" style="width: 93px;">3RD</th>
                <th class="border-top-0" style="width: 93px;">4TH</th>
                <th class="border-top-0" style="width: 93px;">5TH</th>
              </tr>
            </thead>
            <tbody >
            {% for item in items %}
                <tr>
                    <td id="seqtd" style="width: 72px; text-align:right;"></td>
                    <td id="prodtd" style="width: 300px;">
                    <div class="dropdown dropright">
                        <a href="#" class="PIlink" data-toggle="dropdown">{{item.product_no}}<a>
                        <div class="dropdown-menu p-0 m-0 text-center">
                        {% url 'kedititem' id=item.id as edititem_url %}
                        {% url 'kdeleteitem' id=item.id as deleteitem_url %} 
                        <a class="PIdd dropdown-item border border-top-0 border-left-0 border-right-0" href="{{ edititem_url }}">Edit</a>
                        <a class="PIdd dropdown-item border border-top-0 border-left-0 border-right-0 border-bottom-0" href="{{ deleteitem_url }}">Delete</a>
                        </div>
                    </div>
                    </td>
                    <td id="wostd" style="width: 150px;" >{{item.wos_no}}</td>
                    <td id="firsttd" style="width: 93px;" class="S">{{item.first_quantity}}</td>
                    <td id="secondtd" style="width: 93px;" class="S">{{item.second_quantity}}</td>
                    <td id="thirdtd" style="width: 93px;" class="S">{{item.third_quantity}}</td>
                    <td id="fourthtd" style="width: 93px;" class="S">{{item.fourth_quantity}}</td>
                    <td id="fifthtd" style="width: 93px;" class="S">{{item.fifth_quantity}}</td>
                 </tr>
            {% endfor %}
             </tbody>
      </table>
      <!-- The Modal -->
        <div class="modal fade" id="myModal">
            <br><br><br>
            <div class="modal-dialog ">
                <div class="modal-content" >
                
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">New Item</h4>
                        <button type="button" class="close" data-dismiss="modal">×</button>
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body">
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            <div class="form-group" >
                                <div class="row">
                                    <div class="col-12">
                                        {{ form1.product_no|as_crispy_field }}
                                        {{ form1.wos_no|as_crispy_field }}
                                    </div>
                                    {% comment %} <div class="col-6" id="controlDiv"> {% endcomment %}
                                        {{ form1.control_noFK|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                </div>
                                <div class="row">
                                    <div class="col-3">
                                    </div>
                                    <div class="col-6">
                                        {{ form1.first_quantity|as_crispy_field }}
                                    </div>
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.second_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.third_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.fourth_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.fifth_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    <div class="col-1">
                                    </div>
                                </div>
                            </div>

                        
                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                            <input type="hidden" name="form_ctrl" value="dr_item">
                            <button type="submit" class="btn btn-outline-success font-weight-bold" id="createdr">Create</button>
                        </form>
                        <button type="button" class="btn btn-outline-danger font-weight-bold" data-dismiss="modal">Close</button>
                    </div>
                    
                </div>
            </div>
        </div>
        <button id="btn_newItem" class="btn btn-outline-success font-weight-bold m-0" style="position: absolute; bottom: 10px; right: 78px;" data-toggle="modal" data-target="#myModal">+ Add</button>
    </div>
    <div id="remarks_div" style="display: none; position: absolute; top:305px; left:750px; font-size: 24px;"></div>
    <div id="date_div" style="display: none; position: absolute; top:174px !important; left:790px; "></div>
    <div id="customer_div" style="display: none; position: absolute; top:174px !important; left:130px;"></div>
    <div id="signature_div" style="display: none; position: absolute; top:500px; left:760px;">{{signed_by}}</div>
    




    <!-- The Modal -->
        <div class="modal fade" id="myModal1" data-keyboard="false" data-backdrop="static">
            <br><br><br><br><br><br><br><br>
            <div class="modal-dialog modal-lg">
                <div class="modal-content" >
                
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Printing Confirmation!</h4>
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body">
                        <div class="font-weight-bold text-dark" style="font-size:32px;" >Did you print the document properly?</div>
                        
                        
                        
                    </div>
                        <div class="text-danger text-center p-0 m-0">*Please answer correctly.</div>
                    <!-- Modal footer -->
                    <div class="modal-footer text-center">
                        <div class="mx-auto">
                            <button type="button" class="btn btn-outline-success font-weight-bold" data-dismiss="modal" id="printy">YES</button>
                            <span class="text-danger">or</span>
                            <button type="button" class="btn btn-outline-danger font-weight-bold" data-dismiss="modal" id="printn">NO</button>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
     <script>
     
        $(document).ready(function() {
            $('#btn_newItem').focus();
            $('.modal').on('shown.bs.modal', function() {
                $("#id_product_no").focus();
            });
            $('#id_date_created').datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $('table tbody tr').each(function(idx){
                $(this).children(":eq(0)").html(idx + 1);
            });

            val = $('#id_control_no').val();
            $('#id_control_noFK').val(val);
            $('#id_control_noFK').attr('tabIndex', -1);
            
            var S = 0;
            $(".S").each(function() {
                var value = $(this).text();
                if(!isNaN(value) && value.length != 0) {
                    S += parseFloat(value);
                }
            });

            

            var rowCount = $('tbody tr').length;
            if (rowCount > 9){
                $('#btn_newItem').prop('disabled', true);
            } else if (rowCount < 1){
                $('#btn_print').prop('disabled', true);
            } else {
                $('#btn_newItem').prop('disabled', false);
            }
            $('#id_control_no').prop('disabled', true);
           
            if ($('#id_status').val() == "WAITING") {
                $('#id_date_created').prop('disabled', true);
                $('#id_customer').prop('disabled', true);
                $('#id_line').prop('disabled', true);
                $('#btn_newItem').prop('disabled', true);
                $('a').prop('disabled', true);
                $("#id_status option[value='OPEN']").attr('disabled','disabled');
                $("#btn_print").attr('disabled','disabled');
            } else if ($('#id_status').val() == "CLOSED") {
                $('#id_date_created').prop('disabled', true);
                $('#id_customer').prop('disabled', true);
                $('#id_line').prop('disabled', true);
                $('#btn_newItem').prop('disabled', true);
                $('a').prop('disabled', true);
                $("#id_status").attr('disabled','disabled');
                $("#btn_print").attr('disabled','disabled');
            } else if ($('#id_status').val() == "OPEN") {
                $('#id_status').prop('disabled', true);
            }

            $('form').on('submit', function(){
                $('#id_control_no').prop('disabled', false);
                $('#id_date_created').prop('disabled', false);
                $('#id_customer').prop('disabled', false);
                $('#id_status').prop('disabled', false);
                $('#id_line').prop('disabled', false);
            });

            $('#btn_print').on('click', function() {  
                var datep =new Date($('#id_date_created').val());
                var cusp =$("#id_customer").val() + " - " + $("#id_line").val();
                $('#remarks_div').text("TOTAL: " + S);
                $('#date_div').text(('0' + (datep.getMonth()+1)).slice(-2) + "-" + ('0' + datep.getDate()).slice(-2) + "-" + datep.getFullYear());
                $('#customer_div').text(cusp);
                window.print();  
            });

            $('#printy').on('click', function(){
                $("#id_status").val("WAITING");
                $( "#donedr" ).trigger( "click" );
            });
        });

        function afterPrint(){
            $('#myModal1').modal();
        }
        
  </script>
{% endblock content %}

komax/templates/komax/edit.html
{% extends "komax/base.html" %}
{% load crispy_forms_tags %}
{% block title %}ITEM EDIT{% endblock title %}

{% block content %}
    <div class="container-flex m-3 pr-1 pl-1 border border-dark rounded" style="height: 565px;">
    <!-- The Modal -->
        <div class="modal fade" id="myModal" data-keyboard="false" data-backdrop="static">
            <br><br><br>
            <div class="modal-dialog modal">
                <div class="modal-content" >
                
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Item</h4>
                        <!--<button type="button" class="close" data-dismiss="modal">×</button>-->
                    </div>
                    
                    <!-- Modal body -->
                    <div class="modal-body">
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            <div class="form-group" >
                                <div class="row">
                                    <div class="col-12">
                                        {{ form1.product_no|as_crispy_field }}
                                        {{ form1.wos_no|as_crispy_field }}
                                    </div>
                                    {% comment %} <div class="col-6" id="controlDiv"> {% endcomment %}
                                        {{ form1.control_noFK|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                </div>
                                <div class="row">
                                    <div class="col-3">
                                    </div>
                                    <div class="col-6">
                                        {{ form1.first_quantity|as_crispy_field }}
                                    </div>
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.second_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.third_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.fourth_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    {% comment %} <div class="col-2"> {% endcomment %}
                                        {{ form1.fifth_quantity|as_crispy_field }}
                                    {% comment %} </div> {% endcomment %}
                                    <div class="col-1">
                                    </div>
                                </div>
                            </div>

                        
                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                            <input type="hidden" name="form_ctrl" value="dr_item">
                            <button type="submit" class="btn btn-outline-success font-weight-bold" id="createdr">Submit</button>
                        </form>
                        <button type="button" class="btn btn-outline-danger font-weight-bold" data-dismiss="modal" id="btn_close">Close</button>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
     <script>
     
        $(document).ready(function() {
            
            $('#id_control_noFK').attr('tabIndex', -1);
            $('.modal').modal('show');
            $('#btn_close').click(function(){
                window.history.back();
            });
        });
  </script>
{% endblock content %}

komax/templates/komax/login.html
{% extends "komax/base.html" %}
{% load crispy_forms_tags %}
{% block title %}LOGIN{% endblock title %}

{% block content %}
<br>
<div class="m-5">
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        <fieldset class="form-group p-4 border border-dark mx-auto rounded text-center w-50 " >
            <legend class="text-center font-weight-bold h1" style="width: 150px;">Login</legend>
            {{ form|crispy }}
        </fieldset>
        
        <div class="form-group mx-auto m-2 text-center">
            <button type="submit" class="btn btn-outline-dark w-25 shadow-lg">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

komax/templates/komax/logout.html
{% extends "komax/base.html" %}
{% block title %}LOGOUT{% endblock title %}

{% block content %}
{% csrf_token %}

<script type="text/javascript">
    $.get("{% url 'auth' %}", function(resp){
        if (resp == 'loggedIn'){
            $("#lgend").show();
            setTimeout(function() {
                window.location.href="{% url 'login' %}"} ,2000
            );
        } else {
            window.location.href="{% url 'login'%}";
        }
    });
        
</script>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="m-5">
        <fieldset id="lgend" class="form-group p-4 border border-dark mx-auto rounded text-center w-50" style=" display: none">
            <legend class="text-center font-weight-bold h1" style="width: 500px;">Logged Out</legend>
            <div><span class="spinner-border"></span></div>
        </fieldset>
</div>

{% endblock content %}